baseurl = "https://forwards.github.io/"
languageCode = "en-us"
title = "FORWARDS"
# Enable comments by entering your Disqus shortname
disqusShortname = "forwards"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 5
footnotereturnlinkcontents = "â†©"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# Don't pluralize section titles (e.g. Blog -> Blogs)
pluralizelisttitles = false
# keep tag/category names (e.g. useR! not user)
preserveTaxonomyNames = true
# don't canonify URLs so can use http://forwards.github.io/ or https://forwards.github.io/
canonifyURLs = false
# maximum number of items in the RSS feed
rssLimit = 3
ignoreFiles = ["\\.knit\\.md$", "\\.utf8\\.md$", "\\.rmd$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[permalinks]
    blog = "blog/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "R Foundation taskforce on women and other under-represented groups"
    bio = ""
    location = ""
    site_description = "R Foundation taskforce on women and other under-represented groups."
    copyright  = "Forwards. Powered by [blogdown](https://github.com/rstudio/blogdown)/[Hugo](//gohugo.io). Theme based on Icarus by [PPOffice](https://github.com/ppoffice)."
    avatar = "images/forwards.svg"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = ""
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["blog"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/custom.css"]
	custom_js  = ["js/jqueryui-1.11.4/jquery-ui.min.js", 
	              "js/tocify-1.9.1/jquery.tocify.js"]

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"
    
[[params.menu]]
    before = true
    label  = "About"
    link   = "/about/"    

[[params.menu]]
    before = true
    label  = "Data"
    link   = "/data/"

[[params.menu]]
    before = true
    label  = "Blog"
    link   = "/blog/"
    
[[params.menu]]
    before = true
    label  = "Edu"
    link   = "/edu/"  

[[params.menu]]
    before = true
    label  = "Docs"
    link   = "/docs/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = ""


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "forwards"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "R_Forwards"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = false
    tag_cloud = true
